# Should throw exception

def main(x):
    i = 0
    while(i < x):
        i+= 1
    return 1