# Should throw exception

def main(x):
    for i in range(0,x):
        i+= 1
    return 1